"""新增用户工具黑名单表

Revision ID: 3984c0a58931
Revises: ea44b2e60c0c
Create Date: 2026-08-02 23:49:43.234185
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3984c0a58931'
down_revision: Union[str, None] = 'ea44b2e60c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tool_blacklist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tool_blacklist_user_id'), 'user_tool_blacklist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tool_blacklist_user_id'), table_name='user_tool_blacklist')
    op.drop_table('user_tool_blacklist')
    # ### end Alembic commands ###
