"""补充认证模块表

Revision ID: 8a873a7049e3
Revises: 15071c38ae86
Create Date: 2026-07-27 21:00:57.037138
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a873a7049e3'
down_revision: Union[str, None] = '15071c38ae86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('uri', sa.String(length=500), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('execute_time', sa.BigInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_log_create_time'), 'operation_log', ['create_time'], unique=False)
    op.create_index(op.f('ix_operation_log_method'), 'operation_log', ['method'], unique=False)
    op.create_index(op.f('ix_operation_log_module'), 'operation_log', ['module'], unique=False)
    op.create_index(op.f('ix_operation_log_operation'), 'operation_log', ['operation'], unique=False)
    op.create_index(op.f('ix_operation_log_user_id'), 'operation_log', ['user_id'], unique=False)
    op.create_table('user_notification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('read_status', sa.Integer(), nullable=False),
    sa.Column('related_id', sa.String(length=64), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id')
    )
    op.create_index(op.f('ix_user_notification_create_time'), 'user_notification', ['create_time'], unique=False)
    op.create_index(op.f('ix_user_notification_expire_time'), 'user_notification', ['expire_time'], unique=False)
    op.create_index(op.f('ix_user_notification_type'), 'user_notification', ['type'], unique=False)
    op.create_index(op.f('ix_user_notification_user_id'), 'user_notification', ['user_id'], unique=False)
    op.create_table('user_token',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=2000), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expired_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token_user_id'), 'user_token', ['user_id'], unique=False)
    op.alter_column('ai_token_usage', 'input_tokens',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ai_token_usage', 'output_tokens',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ai_token_usage', 'total_tokens',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ai_token_usage', 'cache_creation_tokens',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ai_token_usage', 'cache_read_tokens',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ai_token_usage', 'cost_amount',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('ai_token_usage', 'tool_called',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('ai_token_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_file', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_file', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('knowledge_file', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_file', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memo', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'未分类'::character varying"))
    op.alter_column('memo', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memo', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_memos_status'), table_name='memo')
    op.drop_index(op.f('idx_memos_user_id'), table_name='memo')
    op.create_index(op.f('ix_memo_user_id'), 'memo', ['user_id'], unique=False)
    op.alter_column('tool_audit_log', 'error_msg',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('tool_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tool_audit_log', 'error_msg',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_memo_user_id'), table_name='memo')
    op.create_index(op.f('idx_memos_user_id'), 'memo', ['user_id'], unique=False)
    op.create_index(op.f('idx_memos_status'), 'memo', ['user_id', 'status'], unique=False)
    op.alter_column('memo', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memo', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memo', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'未分类'::character varying"))
    op.alter_column('knowledge_file', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_file', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_file', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('knowledge_file', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_token_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_token_usage', 'tool_called',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('ai_token_usage', 'cost_amount',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('ai_token_usage', 'cache_read_tokens',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ai_token_usage', 'cache_creation_tokens',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ai_token_usage', 'total_tokens',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ai_token_usage', 'output_tokens',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('ai_token_usage', 'input_tokens',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.drop_index(op.f('ix_user_token_user_id'), table_name='user_token')
    op.drop_table('user_token')
    op.drop_index(op.f('ix_user_notification_user_id'), table_name='user_notification')
    op.drop_index(op.f('ix_user_notification_type'), table_name='user_notification')
    op.drop_index(op.f('ix_user_notification_expire_time'), table_name='user_notification')
    op.drop_index(op.f('ix_user_notification_create_time'), table_name='user_notification')
    op.drop_table('user_notification')
    op.drop_index(op.f('ix_operation_log_user_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_operation'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_module'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_method'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_create_time'), table_name='operation_log')
    op.drop_table('operation_log')
    # ### end Alembic commands ###
