"""新增 user_profile 长期记忆用户画像表

Revision ID: ea44b2e60c0c
Revises: b5d225e26d01
Create Date: 2026-08-01 00:02:12.853279
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea44b2e60c0c'
down_revision: Union[str, None] = 'b5d225e26d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index(op.f('ix_user_token_user_id'), table_name='user_token')
    op.drop_table('user_token')
    op.drop_index(op.f('ix_user_notification_create_time'), table_name='user_notification')
    op.drop_index(op.f('ix_user_notification_expire_time'), table_name='user_notification')
    op.drop_index(op.f('ix_user_notification_type'), table_name='user_notification')
    op.drop_index(op.f('ix_user_notification_user_id'), table_name='user_notification')
    op.drop_table('user_notification')
    op.drop_index(op.f('ix_operation_log_create_time'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_method'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_module'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_operation'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_user_id'), table_name='operation_log')
    op.drop_table('operation_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('operation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('uri', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('params', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('execute_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('operation_log_pkey'))
    )
    op.create_index(op.f('ix_operation_log_user_id'), 'operation_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_operation_log_operation'), 'operation_log', ['operation'], unique=False)
    op.create_index(op.f('ix_operation_log_module'), 'operation_log', ['module'], unique=False)
    op.create_index(op.f('ix_operation_log_method'), 'operation_log', ['method'], unique=False)
    op.create_index(op.f('ix_operation_log_create_time'), 'operation_log', ['create_time'], unique=False)
    op.create_table('user_notification',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('read_status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('related_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('extra_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expire_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_notification_pkey')),
    sa.UniqueConstraint('notification_id', name=op.f('user_notification_notification_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_notification_user_id'), 'user_notification', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_notification_type'), 'user_notification', ['type'], unique=False)
    op.create_index(op.f('ix_user_notification_expire_time'), 'user_notification', ['expire_time'], unique=False)
    op.create_index(op.f('ix_user_notification_create_time'), 'user_notification', ['create_time'], unique=False)
    op.create_table('user_token',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expired_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_token_pkey'))
    )
    op.create_index(op.f('ix_user_token_user_id'), 'user_token', ['user_id'], unique=False)
    op.drop_table('user_profile')
    # ### end Alembic commands ###
